// 14 selectable Wau Bulan kite skins, one per Malaysian state (the 13 states
// plus the Federal Territory of Kuala Lumpur - the conventional "14" grouping
// mirrored by the 14 stripes/points on the national flag and star). Each
// palette takes cues from that state's flag/crest colors and drives the
// gradient stops, accent diamond, and ribbon tail colors in
// entities/Player.jsx.
export const KITE_DESIGNS = [
  {
    id: 'johor',
    name: 'Johor',
    from: '#4a6fd8',
    mid: '#0b2f7a',
    to: '#050f33',
    outline: '#e63946',
    accentFrom: '#ffffff',
    accentTo: '#e63946',
    ribbons: ['#e63946', '#ffffff', '#0b2f7a'],
  },
  {
    id: 'kedah',
    name: 'Kedah',
    from: '#ffe08a',
    mid: '#f5c451',
    to: '#8a6413',
    outline: '#1a9c90',
    accentFrom: '#ffffff',
    accentTo: '#f5c451',
    ribbons: ['#1a9c90', '#ffffff', '#8a6413'],
  },
  {
    id: 'kelantan',
    name: 'Kelantan',
    from: '#ff8a8a',
    mid: '#d81e2c',
    to: '#4a0a0f',
    outline: '#ffffff',
    accentFrom: '#ffffff',
    accentTo: '#f5c451',
    ribbons: ['#08060d', '#ffffff', '#d81e2c'],
  },
  {
    id: 'melaka',
    name: 'Melaka',
    from: '#ffd24a',
    mid: '#d81e2c',
    to: '#4a0a0f',
    outline: '#08060d',
    accentFrom: '#ffffff',
    accentTo: '#ffd24a',
    ribbons: ['#08060d', '#ffd24a', '#d81e2c'],
  },
  {
    id: 'negeri-sembilan',
    name: 'Negeri Sembilan',
    from: '#ffe08a',
    mid: '#e2a824',
    to: '#08060d',
    outline: '#d81e2c',
    accentFrom: '#ffe08a',
    accentTo: '#08060d',
    ribbons: ['#08060d', '#d81e2c', '#ffe08a'],
  },
  {
    id: 'pahang',
    name: 'Pahang',
    from: '#f5f6f7',
    mid: '#c7ccd1',
    to: '#1a1c1f',
    outline: '#f5c451',
    accentFrom: '#ffffff',
    accentTo: '#f5c451',
    ribbons: ['#1a1c1f', '#f5c451', '#ffffff'],
  },
  {
    id: 'penang',
    name: 'Penang',
    from: '#a6f2ef',
    mid: '#12b8c4',
    to: '#0a4048',
    outline: '#d81e2c',
    accentFrom: '#ffffff',
    accentTo: '#d81e2c',
    ribbons: ['#d81e2c', '#ffffff', '#12b8c4'],
  },
  {
    id: 'perak',
    name: 'Perak',
    from: '#fff6d8',
    mid: '#f5c451',
    to: '#3a4249',
    outline: '#ffffff',
    accentFrom: '#ffffff',
    accentTo: '#f5c451',
    ribbons: ['#ffffff', '#f5c451', '#3a4249'],
  },
  {
    id: 'perlis',
    name: 'Perlis',
    from: '#fff0c2',
    mid: '#f5c451',
    to: '#0b3d91',
    outline: '#0b3d91',
    accentFrom: '#fff0c2',
    accentTo: '#0b3d91',
    ribbons: ['#0b3d91', '#fff0c2', '#f5c451'],
  },
  {
    id: 'sabah',
    name: 'Sabah',
    from: '#9fd8ff',
    mid: '#1e7fd8',
    to: '#0b2f5c',
    outline: '#ff8c3f',
    accentFrom: '#ffe08a',
    accentTo: '#ff8c3f',
    ribbons: ['#ff8c3f', '#ffffff', '#1e7fd8'],
  },
  {
    id: 'sarawak',
    name: 'Sarawak',
    from: '#ffe08a',
    mid: '#f5c451',
    to: '#08060d',
    outline: '#d81e2c',
    accentFrom: '#ffe08a',
    accentTo: '#f5c451',
    ribbons: ['#08060d', '#d81e2c', '#ffe08a'],
  },
  {
    id: 'selangor',
    name: 'Selangor',
    from: '#ffd24a',
    mid: '#d81e2c',
    to: '#7a0e15',
    outline: '#ffe08a',
    accentFrom: '#ffe08a',
    accentTo: '#ffd24a',
    ribbons: ['#d81e2c', '#ffe08a', '#ffd24a'],
  },
  {
    id: 'terengganu',
    name: 'Terengganu',
    from: '#f5f6f7',
    mid: '#c7ccd1',
    to: '#08060d',
    outline: '#f5c451',
    accentFrom: '#ffffff',
    accentTo: '#f5c451',
    ribbons: ['#08060d', '#ffffff', '#f5c451'],
  },
  {
    id: 'kuala-lumpur',
    name: 'Kuala Lumpur',
    from: '#9fd8ff',
    mid: '#0b3d91',
    to: '#08060d',
    outline: '#ffd24a',
    accentFrom: '#ffffff',
    accentTo: '#d81e2c',
    ribbons: ['#d81e2c', '#ffd24a', '#0b3d91'],
  },
]

export const DEFAULT_KITE_ID = KITE_DESIGNS[0].id

export function getKiteDesign(id) {
  return KITE_DESIGNS.find((k) => k.id === id) ?? KITE_DESIGNS[0]
}
